x-common-env: &common-env
  TZ: Asia/Seoul

x-healthcheck-defaults: &healthcheck-defaults
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 30s

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    env_file:
      - envs/database.env
    ports:
      - 5432:5432
    environment:
      <<: *common-env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      <<: *healthcheck-defaults
    networks:
      - postgres-network
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    environment:
      <<: *common-env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      <<: *healthcheck-defaults
    networks:
      - redis-network
  kafka:
    image: apache/kafka-native:latest
    container_name: kafka
    env_file:
      - envs/kafka.env
    ports:
      - 9092:9092
    environment:
      <<: *common-env
    networks:
      - kafka-network

networks:
  postgres-network:
    name: postgres-network
    driver: bridge
  redis-network:
    name: redis-network
    driver: bridge
  kafka-network:
    name: kafka-network
    driver: bridge